name: gymgym
description: "Go Gym Brother"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.1

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true

flutter_icons:
  ios: true
  android: false
  image_path: "assets/logo.png"