name: gym_me
description: "Go Gym Brother"

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.3"
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.1
  build_runner: ^2.3.3
  hive_generator: ^1.1.3


flutter:
  assets:
    - assets/logo.png
    - assets/images/
    - assets/exercises.json
  uses-material-design: true

flutter_icons:
  ios: true
  android: false
  image_path: "assets/logo.png"